### ISSUE TITLE
Data download difficulty

### ISSUE THREAD

**Issue by lgpgood** [GRAP-UdL-AT/RGBD_fruit_detection_faster-rcnn.pytorch#1]
Hello, the author, it is basically difficult to download good data from the data website you give, the data is often half downloaded to stop downloading. Could you give me another data link that you can download? thank you

**Comment by Jordi-Gene-Mola** [comment]
Hello @lgpgood. Thank you for your message. I have tried the data link and it works. Could you try it again?
