### ISSUE TITLE
Kfuji RGB-DS database raw point cloud

### ISSUE THREAD

**Issue by Lyhour-Chhay** [GRAP-UdL-AT/RGBD_fruit_detection_faster-rcnn.pytorch#2]
I am very interested in your work. I have been downloaded the dataset and the source code from the link on your paper for practical. However, I have some questions related to your dataset:

    1.	the ptCloud in .m file of raw data, there is 8 column. What each column represent for? Do they represent the world coordinate X,Y,Z?
 
    2.	How do you generate the preprocess data corresponding to the point cloud? Does the point cloud in the raw data used for generating the depth information? I know that the Microsoft Kinect generates the RGB, Depth, and IR. I may confuse about your preprocess data because of the point cloud.

**Comment by Jordi-Gene-Mola** [comment]
Dear Chhay Lyhour, thank you for your interest. In the following I respond your questions:
    1)    The matrix saved in the .mat file is structured with the following columns: [X, Y, Z, R, G, B, IR, IRc]. Where [X, Y, Z] are the 3D coordinates of each point, [R G B] is the colour of each point, IR is the infrared light intensity received from each point, and IRc is the range corrected IR light intensity: IRc = IR*(sqrt(X^2+Y^2+Z^2))^2 = IR*(X^2+Y^2+Z^2).
    2)    As you commented, the Microsoft Kinect directly generates the RGB, depth and IR. However, the team that acquired the data used a software that only saved a RGB image and a point cloud. In consequence, we had to project the point cloud onto the image plane in order to obtain the depth and IR images. If we would repeat the experiment, we would directly save the depth and IR images. In conclusion: if you are planning to acquire new data, I suggest you to directly use the depth and IR images provided by Kinect.
Best Regards, Jordi
